global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'application'
    scrape_interval: 15s
    scrape_timeout: 15s  # Augmentation du timeout
    static_configs:
      - targets: ['192.168.49.2:30461']
    metrics_path: '/metrics'